### ISSUE TITLE
[feat] 챌린지 report 기능

### ISSUE THREAD

**Issue by sudosoo** [TeamFair/meokQ-backend#202]
현재 ‘인증’탭에 누구나 사진을 업로드 할 수 있는 구조이다. 이에 따라 퀘스트에 맞지 않거나 특정 인원에게 불쾌한 사진을 제공 할 수도 있다는 문제점을 발견하였다. 추가로 유저가 올린 컨텐츠를 신고하는 기능이 앱 출시하는데 필요하다고 알고있다.

해당 계정 차단/알고리즘최적화 등 방법을 적용한다면 공수가 많이 들기에 1차 디벨롶에서는 신고 시 운영측에 알리는 역할로 개발을 진행한다.

TO-BE:

신고하기 적용 > 해당 챌린지 status: report 처리 [신규]

[CUSTOMER]

1. 확인 클릭 시 인증탭 새로고침 / 해당 게시물 status report로 변경.
2. 인증 탭에서 status가 report면 보여지지 않습니다.

[ADMIN]
1. 신고 탭에서 신고된 챌린지들이 조회됩니다. (status == report일 경우) [신규 탭 생성 필요] 
2. 운영자는 확인 후 챌린지의 status를 변경할 수 있습니다 (완료, 삭제=미완료)

-------------
사용자
-챌린지 신고 api 
[POST] api/customer/challenge/report
어드민 
- 신고된 챌린지 조회 api 
[GET] api/customer/challenge/report
- 삭제 or 재등록  (삭제api 는 있으므로 등록상태로 변경할 api 추가 )

**Comment by youngyin** [comment]
@sudosoo 상태 정보를 [statusV1.0.drawio](https://drive.google.com/file/d/1Anzf5qLjkeeiXEBcah-Gqi5XsGPI-SxX/view?usp=sharing)문서에서 관리하고 있습니다. 아래 문서에 상태정보 업데이트 부탁드립니다.
편집권한은 gmail 알려주시면 추가해두겠습니다. slack으로 계정 공유부탁드립니다.
